### ISSUE TITLE
How many images did you use for your training data?

### ISSUE THREAD

**Issue by Armitage87** [puneet29/StyleTransferApp#1]
I tried replicating some of your results with different style images, and I used 2, 4, 50 and 100 epochs with 100 training images, and results were pretty disappointing.  Could you offer some guidance on how many training images did you use?

**Comment by puneet29** [comment]
Hey @Armitage87 !
Sorry for the late reply.
### Possible Problem:
If you followed my technique of training the model for a particular style image using:
```shell
python train.py --dataset </path/to/train-dataset> --style-image </path/to/style/image> --save-model-dir </path/to/save-model/folder> --epochs 2 --cuda 1
```
then the problem might be related to the style and content weight.
### Possible Solution:
You need to set different style weight and content weight depending on the style image you are training on. You can start by using style weight of `5e10` or `1e11`. Try out different weights. Also, you'll see good results by 2 epochs, so check different weights by training for 2 epochs.

I used COCO dataset for training and it contains about 118k images. You can use the same. :)
Hope this resolves the issue.

**Comment by Armitage87** [comment]
Cheers mate, I'll give it a go. I was training with extremely limited data set and trying different hyperparams, but coco dataset makes much more sense
