### ISSUE TITLE
TypeError: can't convert CUDA tensor to numpy

### ISSUE THREAD

**Issue by stvoler** [puneet29/StyleTransferApp#2]
Hello) 
When i stylish image width GPU: 

PS D:\neuro\StyleTransferApp> python stylize.py --content-image images/content/ju1.jpg --model model/save-model/last-model.model --output-image images/output/ju-fin.jpg --cuda 1
Traceback (most recent call last):
  File "stylize.py", line 66, in <module>
    stylize(args)
  File "stylize.py", line 38, in stylize
    content_image = match_size(content_image, output)
  File "D:\neuro\StyleTransferApp\utils.py", line 34, in match_size
    img = image.clone().clamp(0, 255).numpy()
TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

Help me please

**Comment by stvoler** [comment]
figured out)
need to replace 
"img = image.clone().clamp(0, 255).numpy()"
to 
"img = image.clone().clamp(0, 255).cpu().numpy()"

**Comment by xXchrizzoXx** [comment]
> figured out)
> need to replace
> "img = image.clone().clamp(0, 255).numpy()"
> to
> "img = image.clone().clamp(0, 255).cpu().numpy()"

If I swap in this line, it works for me, but it takes longer than CPU xD
CPU ~3.5 sec
GPU ~7.5 sec
