### ISSUE TITLE
Number of epochs

### ISSUE THREAD

**Issue by AlexanderGeng** [puneet29/StyleTransferApp#4]
Hi,

@puneet29  is there any reason why you choose 2 epochs and not 10 or 20 or only 1 epoch?
Should this have not better results?

Best regards.
Alex

**Comment by puneet29** [comment]
Hi Alex!

Thank you for having a look at this repo. Usually, around 2-3 epochs will be enough for nn to learn the appropriate weights for style transfer. However, you can experiment with doing more no. of epochs for your training. I don't think there will be any significant difference between results of the epoch2 model and the epoch 10/20 model.

Regards,
Puneet
