### ISSUE TITLE
Help: Setting up the "train" mode

### ISSUE THREAD

**Issue by xXchrizzoXx** [puneet29/StyleTransferApp#5]
Greetings puneet29,

first of all, thank you very much for your cli implementation of Style Transfer! It's the first Style Transfer I was able to start (I'm a python/ ML noob). So thank you very much for this. To stylize and image or an image sequence with one of you stylize models was no problem and it's really fast! :)
Unfortunately, I don't have enough experience to get the training mode to work.
Could you help me a with setting up the train.py?

**I try to put this in the command line:** 
`python train.py --dataset 'C:\Style Transfer Test\StyleTransferApp-master\training_sets\test2014' --style-image 'H:/Houdini/Houdini Projects/Filmakademie/Diplom/Erklaerpassagen/referenzen/Night Shadows - Edward Hopper_croped.jpg' --save-model-dir 'C:\Style Transfer Test\StyleTransferApp-master\Stylize_models\' --epochs 2 --cuda 0 --checkpoint-model-dir 'C:\Style Transfer Test\StyleTransferApp-master\Stylize_models\checkpoints'`

**The error message I got was:** 
`usage: train.py [-h] [--epochs EPOCHS] [--batch-size BATCH_SIZE] --dataset DATASET [--style-image STYLE_IMAGE]
                --save-model-dir SAVE_MODEL_DIR [--checkpoint-model-dir CHECKPOINT_MODEL_DIR]
                [--image-size IMAGE_SIZE] [--style-size STYLE_SIZE] [--cuda CUDA] [--seed SEED]
                [--content-weight CONTENT_WEIGHT] [--style-weight STYLE_WEIGHT] [--lr LR]
                [--log-interval LOG_INTERVAL] [--checkpoint-interval CHECKPOINT_INTERVAL]
train.py: error: unrecognized arguments: Transfer Test\StyleTransferApp-master\Stylize_models\checkpoints`

**So I didn't set a path for the checkpoints and tried to execute the script with this command:**
`python train.py --dataset 'C:\Style Transfer Test\StyleTransferApp-master\training_sets\test2014' --style-image 'H:/Houdini/Houdini Projects/Filmakademie/Diplom/Erklaerpassagen/referenzen/Night Shadows - Edward Hopper_croped.jpg' --save-model-dir 'C:\Style Transfer Test\StyleTransferApp-master\Stylize_models\' --epochs 2 --cuda 0`

**The error was:**
`[WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Style Transfer Test\\StyleTransferApp-master\\Stylize_models" --epochs 2 --cuda 0'`

**Then I tried:**
`python train.py --dataset 'C:\Style Transfer Test\StyleTransferApp-master\training_sets\test2014' --style-image 'H:/Houdini/Houdini Projects/Filmakademie/Diplom/Erklaerpassagen/referenzen/Night Shadows - Edward Hopper_croped.jpg' --save-model-dir 'C:\Style Transfer Test\StyleTransferApp-master\Stylize_models\Night_Shadow.model' --epochs 2`

**And the error I got was:**
`Traceback (most recent call last):
  File "train.py", line 183, in <module>
    train(args)
  File "train.py", line 47, in train
    train_dataset = datasets.ImageFolder(args.dataset, transform=transform)
  File "C:\Users\Chrizzo\AppData\Local\Programs\Python\Python38\lib\site-packages\torchvision\datasets\folder.py", line 226, in __init__
    super(ImageFolder, self).__init__(root, loader, IMG_EXTENSIONS if is_valid_file is None else None,
  File "C:\Users\Chrizzo\AppData\Local\Programs\Python\Python38\lib\site-packages\torchvision\datasets\folder.py", line 114, in __init__
    raise RuntimeError(msg)
RuntimeError: Found 0 files in subfolders of: C:\Style Transfer Test\StyleTransferApp-master\training_sets\test2014
Supported extensions are: .jpg,.jpeg,.png,.ppm,.bmp,.pgm,.tif,.tiff,.webp`

I'm not quite sure, what I haven to do. Especially, how I have to pipe in the training data sets. Do I have to just write the path where the data is saved, do I have to unpack the archive, do I have to write the path where the archive is saved AND the filename plus file extension? Because none of this works.
So, can you please help me?

Best Regards,
Chris

**Comment by puneet29** [comment]
Hi @xXchrizzoXx 

Thank you for taking a look at the repo. Your words mean a lot.
So, I checked my archive codes. The dataset needs to be the location of the folder where the train2014 folder is stored. So if the structure is `folder_name/train2014/` then the argument `--dataset folder_name`.
In your case, it must be `training_sets`.
Also the `--save-model-dir` must be the directory in which you want the model to be stored.

**I feel like there's some problem in parsing the arguments**. Probably argparse doesn't take spaces into account. I would recommend you to **try putting every single file and folder in the same folder and then using relative paths rather than the full path.** Hope it helps.

If it works please do tell, then it needs a few fixes in the code. I've got a few things up my sleeves right now but I will fix the code later. Thank you once again!

**Comment by xXchrizzoXx** [comment]
> Hi @xXchrizzoXx
> 
> Thank you for taking a look at the repo. Your words mean a lot.
> So, I checked my archive codes. The dataset needs to be the location of the folder where the train2014 folder is stored. So if the structure is `folder_name/train2014/` then the argument `--dataset folder_name`.
> In your case, it must be `training_sets`.
> Also the `--save-model-dir` must be the directory in which you want the model to be stored.
> 
> **I feel like there's some problem in parsing the arguments**. Probably argparse doesn't take spaces into account. I would recommend you to **try putting every single file and folder in the same folder and then using relative paths rather than the full path.** Hope it helps.
> 
> If it works please do tell, then it needs a few fixes in the code. I've got a few things up my sleeves right now but I will fix the code later. Thank you once again!

Hey puneet29, thank you for the quick reply! I got it to work... now I just have to wait, haha.
If that works, my next task is to get "cuda mode on" to run :D

Oh and for anyone wondering, this command worked for me:
`python train.py --dataset 'C:/Style Transfer Test/StyleTransferApp-master/training_sets' --style-image 'H:/Houdini/Houdini Projects/Filmakademie/Diplom/Erklaerpassagen/referenzen/Night Shadows - Edward Hopper_croped.jpg' --save-model-dir 'C:/Style Transfer Test/StyleTransferApp-master/Stylize_models/' --epochs 2 --cuda 0 --checkpoint-model-dir 'C:\Style Transfer Test\StyleTransferApp-master\Stylize_models\checkpoints'`

**Comment by puneet29** [comment]
Thanks for clearing out @xXchrizzoXx 
Closing the issue as it is resolved.
